#TOKEN
ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"

#SQL
SPRING_DATASOURCE_URL: "jdbc:mysql://localhost:3306/civicappdatabase?createDatabaseIfNotExist=true"
SPRING_DATASOURCE_USERNAME: "root"
SPRING_DATASOURCE_PASSWORD: "332003"
SPRING_DATASOURCE_DRIVER: "com.mysql.cj.jdbc.Driver"

#RABBITMQ
RABBITMQ_DEFAULT_USER: "guest"
RABBITMQ_DEFAULT_PASS: "guest"

BASE_PORT: 8081
CLIENT_URL: "http://localhost:5173"

#GOOGLE
CLIENT_ID: "39476822030-m15g24ckmabv4h6dbfjb7ir5bu40ovgi.apps.googleusercontent.com"

#VideoSDK API
VIDEOSDK_API_KEY: "49d47493-9aad-4718-8757-ebcd1e28422a"
VIDEOSDK_SECRET_KEY: "4c2e42c3b02038be41ac5317afac000e6341e09ef08d565bf67c1f2b9f02ffc5"
VIDEOSDK_API_ENDPOINT: "https://api.videosdk.live/v2"



